version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongodb_data_container:/data/db

  api: 
    image: warranty-api
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb
    links:
      - mongodb
    restart: on-failure

volumes:
  mongodb_data_container: